<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE collection[
    <!ELEMENT collection (description, recipe*)>

    <!ELEMENT description (#PCDATA)>
    <!ELEMENT recipe (title, ingredient*, preparation, comment?, nutrition)>

    <!ELEMENT title (#PCDATA)>
    <!ELEMENT ingredient EMPTY>

    <!ATTLIST ingredient name CDATA #REQUIRED>
    <!ATTLIST ingredient amount CDATA #IMPLIED>
    <!ATTLIST ingredient unit (kg|gr|pieces|spoons) #IMPLIED>

    <!ELEMENT preparation (step+)>
    <!ELEMENT step (#PCDATA)>

    <!ELEMENT comment (#PCDATA)>

    <!ELEMENT nutrition EMPTY>
    <!ATTLIST nutrition calories CDATA #REQUIRED>
    <!ATTLIST nutrition fat CDATA #REQUIRED>
    <!ATTLIST nutrition carbohydrates CDATA #REQUIRED>
    <!ATTLIST nutrition protein CDATA #REQUIRED>
]>

<collection>
    <description>Some description here</description>
    <recipe>
        <title>Beef</title>
        <ingredient name="Beef Steak" amount="0.7" unit="kg" />
        <ingredient name="Parmesan" amount="200" unit="gr" />
        <ingredient name="Garlic" amount="5" unit="pieces" />
        <ingredient name="Savory" amount="20" unit="gr" />
        <ingredient name="Olive oil" amount="4" unit="spoons" />
        <ingredient name="Salt" />

        <preparation>
            <step>Preheat the oven</step>
            <step>Mix all products</step>
            <step>Bake 50 minutes</step>
        </preparation>

        <comment>Optional comment</comment>
        <nutrition calories="1234" fat="28" carbohydrates="43" protein="35" />
    </recipe>
    <recipe>
        <title>Pork</title>
        <ingredient name="Beef Steak" amount="0.7" unit="kg" />
        <ingredient name="Parmesan" amount="200" unit="gr" />
        <ingredient name="Garlic" amount="5" unit="pieces" />

        <preparation>
            <step>Preheat the oven</step>
        </preparation>
        <nutrition calories="1234" fat="28" carbohydrates="43" protein="35" />
    </recipe>
</collection>